---
name: Algorithm-Voting
version: 0.01
author:
  - 'Holmescorp Software Dev Team <softwaredevelopment@holmescorp.com>'
abstract: The great new Algorithm::Voting!
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  List::Util: 0
build_requires:
  Carp: 0
  Class::Accessor: 0
  Data::Dumper: 0
  List::Util: 0
  Test::Exception: 0
  Test::More: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
provides:
  Algorithm::Voting:
    file: lib/Algorithm/Voting.pm
    version: 0.01
generated_by: Module::Build version 0.280802
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
